# Generated by Django 4.2 on 2024-01-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_car_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='horse_power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
